openapi: 3.0.1
info:
  title: Apoteksapp Backend Pharmacy API
  description: Apoteksapp Backend Pharmacy API
  version: "0.6"
servers:
  - url: http://localhost:8086
    description: Generated server url
tags:
  - name: pharmacy
    description: ASP Pharmacy API
paths:
  /api/v1/pharmacy/{pharmacyNumber}/getorders:
    post:
      tags:
        - pharmacy
      summary: Hent ordreliste
      description: Henter ordreliste hørende til CPR-nummer
      operationId: getOrders
      parameters:
        - name: createdSince
          in: query
          description: Tidsbegrænset søgning
          required: false
          schema:
            type: string
            format: date-time
          example: 2020-06-21T01:23:45.123Z
        - name: orderStatus
          in: query
          description: Ordrestatus-filter
          required: false
          schema:
            type: string
            enum:
              - PENDING
              - APPROVED
              - PACKAGED
              - READY_FOR_PICKUP
              - SENT
              - DELIVERED
              - CANCELLED
          example: READY_FOR_PICKUP
        - name: limit
          in: query
          description: "Max antal resultater (max 50, default 10)"
          required: false
          schema:
            type: integer
            format: int32
            default: 10
          example: 5
        - name: pharmacyNumber
          in: path
          description: 5-cifret apoteksnummer
          required: true
          schema:
            type: string
          example: "00300"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetOrdersRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrdersResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
  /api/v1/pharmacy/{pharmacyNumber}/getuserconsent:
    post:
      tags:
        - pharmacy
      summary: Hent samtykkeoplysninger
      description: Henter oplysninger om brugerens favoritapotek samt brug af app'en
      operationId: getConsent
      parameters:
        - name: pharmacyNumber
          in: path
          description: 5-cifret apoteksnummer
          required: true
          schema:
            type: string
          example: "00300"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
  /api/v1/pharmacy/{pharmacyNumber}/getuserinfo:
    post:
      tags:
        - pharmacy
      summary: Hent brugerinformation
      description: Henter oplysninger om brugerens favoritapotek samt brug af app'en
      operationId: getUserInfo
      parameters:
        - name: includeConsent
          in: query
          description: Inkludér samtykke-oplysninger
          required: false
          schema:
            type: boolean
            default: false
          example: true
        - name: pharmacyNumber
          in: path
          description: 5-cifret apoteksnummer
          required: true
          schema:
            type: string
          example: "00300"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
  /api/v1/pharmacy/{pharmacyNumber}/order/{orderId}:
    put:
      tags:
        - pharmacy
      summary: Opdater ordre
      description: "Hent samtykker, som borgeren har afgivet i forhold til app'en"
      operationId: updateOrderStatus
      parameters:
        - name: pharmacyNumber
          in: path
          description: 5-cifret apoteksnummer
          required: true
          schema:
            type: string
          example: "00300"
        - name: orderId
          in: path
          description: Ordre-id
          required: true
          schema:
            type: string
          example: 1234
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderStatusRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
components:
  schemas:
    ApiError:
      required:
        - errorCode
        - message
      type: object
      properties:
        errorCode:
          type: string
          description: An identifiable error code
          example: APP_100
        message:
          type: string
          description: A description of the error
          example: Invalid format of id
    Consent:
      required:
        - consentDateTime
        - fullConsentText
        - heading
        - id
      type: object
      properties:
        id:
          maxLength: 50
          type: string
          description: Id på samtykke
          example: ST-12
        heading:
          maxLength: 50
          type: string
          description: Overskrift på samtykke
          example: Privatlivs- og samtykkeerklæring
        fullConsentText:
          maxLength: 65535
          type: string
          description: Fuld samtykketekst
          example: "Jeg giver hermed samtykke til, at de databehandlere, der er næ\
            vnt nedenfor, indsamler og behandler personoplysninger om mig, når jeg..."
        consentDateTime:
          type: string
          description: Samtykke-tidspunkt
          format: date-time
      description: Borgerens samtykker
    ConsentRequest:
      required:
        - cpr
      type: object
      properties:
        cpr:
          type: string
          description: CPR-nummer uden bindestreg
          example: "0101010101"
    ConsentResponse:
      type: object
      properties:
        consentList:
          type: array
          description: Borgerens samtykker
          items:
            $ref: '#/components/schemas/Consent'
    DeliveryInformation:
      required:
        - deliveryType
      type: object
      properties:
        deliveryType:
          type: string
          description: Leveringsmetode
          enum:
            - GLS
            - GLS_TO_DOOR
            - POSTNORD
            - POSTNORD_TO_DOOR
            - PHARMACY_DELIVERY
            - PHARMACY_PICKUP
            - DELIVERY_LOCATION_PICKUP
        deliveryPrice:
          type: integer
          description: Pris for udlevering (i ører)
          format: int64
          example: 1500
        parcelShopNumber:
          maxLength: 20
          type: string
          description: Id på pakkeshop
          example: "96606"
        deliveryAddress:
          maxLength: 100
          type: string
          description: Modtageradresse fritekst (uden postnr/by)
          example: Privatvej 42
        deliveryZip:
          maxLength: 10
          type: string
          description: "Modtageradresse, postnummer"
          example: "4200"
        deliveryCity:
          maxLength: 100
          type: string
          description: "Modtageradresse, bynavn"
          example: Bysted
      description: Leveringsoplysninger
    GetOrdersRequest:
      required:
        - cpr
      type: object
      properties:
        cpr:
          type: string
          description: CPR-nummer uden bindestreg
          example: "0101010101"
    GetOrdersResponse:
      type: object
      properties:
        orders:
          type: array
          description: Liste af ordrer
          items:
            $ref: '#/components/schemas/Order'
    Order:
      required:
        - deliveryInformation
        - orderEntries
        - orderId
        - orderStatus
        - paymentMethod
      type: object
      properties:
        orderId:
          maxLength: 20
          type: string
          description: Ordrens id
          example: "1234"
        orderEntries:
          type: array
          description: Ordrens bestanddele
          items:
            $ref: '#/components/schemas/OrderEntry'
        orderStatus:
          type: string
          description: Ordrens status
          example: SENT
          enum:
            - PENDING
            - APPROVED
            - PACKAGED
            - READY_FOR_PICKUP
            - SENT
            - DELIVERED
            - CANCELLED
        paymentMethod:
          type: string
          description: Betalingsmetode
          example: BY_AGREEMENT
          enum:
            - BY_AGREEMENT
            - BY_PICKUP
        deliveryInformation:
          $ref: '#/components/schemas/DeliveryInformation'
      description: Liste af ordrer
    OrderEntry:
      required:
        - fmkOrderId
        - packageCount
        - packageNumber
      type: object
      properties:
        fmkOrderId:
          maxLength: 20
          type: integer
          description: Ordrens FMK-id
          format: int64
          example: 1234
        packageNumber:
          maxLength: 6
          type: integer
          description: "Varenummeret, som ordren omhandler"
          format: int64
          example: 504878
        packageCount:
          maxLength: 10
          type: integer
          description: "Antal pakninger, som ordren omhandler"
          format: int64
          example: 1
      description: Ordrens bestanddele
    UpdateOrderStatusRequest:
      required:
        - cpr
        - status
      type: object
      properties:
        cpr:
          maxLength: 10
          type: string
          description: CPR-nummer uden bindestreg
          example: "0101010101"
        status:
          type: string
          description: Ny ordrestatus
          example: CANCELLED
          enum:
            - PENDING
            - APPROVED
            - PACKAGED
            - READY_FOR_PICKUP
            - SENT
            - DELIVERED
            - CANCELLED
        statusRemark:
          maxLength: 100
          type: string
          description: "Kommentar til ordrestatus, fx annulleringsårsag"
          example: Annulleret efter borgers ønske
    UserInfo:
      required:
        - appUser
        - favouritePharmacy
      type: object
      properties:
        appUser:
          type: boolean
          description: "true hvis borgeren er registreret som bruger af app'en, eller\
            \ false"
          example: true
        favouritePharmacy:
          type: string
          description: "YES (hvis det forespørgende apotek er borgerens favoritapotek,\
            \ dvs de første tre cifre af apoteksnummeret matcher), NO (hvis borgeren\
            \ ikke har valgt), OTHER (hvis borgeren er tilknyttet et andet favoritapotek)"
          example: "YES"
          enum:
            - "YES"
            - "NO"
            - OTHER
        favouritePharmacyNumber:
          maxLength: 5
          type: string
          description: Favoritapotek. Kun udfyldt hvis kaldende apotek er i samme
            koncern som favoritapotek
          example: "00300"
        consentList:
          type: array
          description: Borgerens samtykker
          items:
            $ref: '#/components/schemas/Consent'
    UserInfoRequest:
      required:
        - cpr
        - pharmacyNumber
      type: object
      properties:
        cpr:
          maxLength: 10
          type: string
          description: CPR-nummer uden bindestreg
          example: "0101010101"
        pharmacyNumber:
          maxLength: 5
          type: string
          description: 5-cifret apoteksnummer for kaldende apotek
          example: "00300"
