openapi: 3.0.1
info:
  title: Apoteksapp Pharmacy API
  description: Service API
  version: "0.6"
servers:
  - url: http://localhost:8087
    description: Generated server url
tags:
  - name: pharmacy
    description: Pharmacy API
security:
  - basicAuth: [ ]
paths:
  /api/v1/pharmacy/{pharmacyNumber}/payment-agreement:
    post:
      tags:
        - pharmacy
      summary: Get payment agreement
      description: "Fetch a user's existing payment agreement, if it exists"
      operationId: getPaymentAgreement
      parameters:
        - name: pharmacyNumber
          in: path
          description: Pharmacy number
          required: true
          schema:
            type: string
          example: "02400"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentAgreementRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentAgreementResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
  /api/v1/pharmacy/{pharmacyNumber}/payment-agreement/create:
    post:
      tags:
        - pharmacy
      summary: Request a payment agreement creation URL
      description: Request a URL that can be used by the user to create a new payment
        agreement
      operationId: createPaymentAgreementURL
      parameters:
        - name: pharmacyNumber
          in: path
          description: Pharmacy number
          required: true
          schema:
            type: string
          example: "02400"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentAgreementRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePaymentAgreementResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
  /api/v1/pharmacy/{pharmacyNumber}/prices:
    post:
      tags:
        - pharmacy
      summary: Look up prices for a specific citizen
      description: "Given one or more package numbers, returns the price for each.\
        \ The price can also take into account the specified citizen's CTR balance"
      operationId: getCitizenSpecificPrices
      parameters:
        - name: pharmacyNumber
          in: path
          description: Pharmacy number
          required: true
          schema:
            type: string
          example: "02400"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitizenSpecificPricesRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitizenSpecificPricesResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
  /api/v1/pharmacy/{pharmacyNumber}/stockcount:
    post:
      tags:
        - pharmacy
      summary: Look up stock count
      description: "Given one or more package numbers, returns the stock count for\
        \ each"
      operationId: getStockCount
      parameters:
        - name: pharmacyNumber
          in: path
          description: Pharmacy number
          required: true
          schema:
            type: string
          example: "02400"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockCountRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockCountResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "404":
          description: Not found
components:
  schemas:
    ApiError:
      required:
        - errorCode
        - message
      type: object
      properties:
        errorCode:
          type: string
          description: An identifiable error code
          example: APP_100
        message:
          type: string
          description: A description of the error
          example: Invalid format of id
    CitizenSpecificPricesRequest:
      required:
        - cpr
        - includeCtrContribution
        - packages
        - totalPurchase
      type: object
      properties:
        includeCtrContribution:
          type: boolean
          description: Indicates whether the returned prices should take the citizen's
            CTR balance into account
          example: true
        totalPurchase:
          type: boolean
          description: Indicates whether the items included in packages should be
            seen as a total purchase or not
          example: true
        cpr:
          pattern: "^\\d{10}$"
          type: string
          description: CPR of the citizen (no dash)
          example: "1507502756"
        packages:
          type: array
          description: List of package numbers and the quantity of each
          items:
            $ref: '#/components/schemas/Package'
    CitizenSpecificPricesResponse:
      required:
        - ctrBalance
        - prices
      type: object
      properties:
        ctrBalance:
          type: integer
          description: CTR balance in ører (1/100 DKK)
          format: int64
          example: 13195
        ctrPeriodEndDate:
          type: string
          description: Date when the current CTR period ends. Can be null if the user has no current balance.
          format: date
          example: 2020-09-14
        prices:
          type: array
          description: Price specification of the individual packages
          items:
            $ref: '#/components/schemas/PriceSpecification'
    CreatePaymentAgreementRequest:
      required:
        - cpr
        - email
      type: object
      properties:
        cpr:
          pattern: "^\\d{10}$"
          type: string
          description: CPR of the citizen (no dash)
          example: "1507502756"
        email:
          type: string
          description: Email
          example: me@mydomain.com
        phone:
          type: string
          description: Phone number
          example: "12345678"
    CreatePaymentAgreementResponse:
      required:
        - agreementDisplayName
        - agreementSystemName
        - url
      type: object
      properties:
        url:
          type: string
          description: URL for creation of payment agreement
          example: https://create.paymentagreement.com
        agreementSystemName:
          type: string
          description: Machine-readable name of the payment agreement
          example: farpay
        agreementDisplayName:
          type: string
          description: Human-readable name of the payment agreement
          example: Farpay betalingsaftale
    Package:
      required:
        - packageNumber
        - quantity
      type: object
      properties:
        packageNumber:
          type: integer
          description: Package number
          format: int32
          example: 522003
        quantity:
          type: integer
          description: The quantity of the specified package number
          format: int32
      description: List of package numbers and the quantity of each
    PaymentAgreementRequest:
      required:
        - cpr
      type: object
      properties:
        cpr:
          pattern: "^\\d{10}$"
          type: string
          description: CPR of the citizen (no dash)
          example: "1507502756"
    PaymentAgreementResponse:
      required:
        - hasAgreement
      type: object
      properties:
        hasAgreement:
          type: boolean
          description: Indicates whether or not the user has a payment agreement
          example: true
        agreementSystemName:
          type: string
          description: Machine-readable name of the payment agreement
          example: farpay
        agreementDisplayName:
          type: string
          description: Human-readable name of the payment agreement
          example: Farpay betalingsaftale
    PriceSpecification:
      required:
        - packageNumber
        - price
      type: object
      properties:
        packageNumber:
          type: integer
          description: Package number
          format: int32
          example: 522003
        price:
          type: integer
          description: CTR adjusted price in ører (1/100 DKK)
          format: int64
          example: 3195
        ctrContribution:
          type: integer
          description: CTR contribution in ører (1/100 DKK). Can be null if the amount cannot be calculated in advance.
          format: int64
          example: 600
      description: Price specification of the individual packages
    StockCount:
      required:
        - packageNumber
        - stockCount
      type: object
      properties:
        packageNumber:
          type: integer
          description: Package number
          format: int32
          example: 522003
        stockCount:
          type: integer
          description: The quantity of the given package number currently in stock
          format: int32
          example: 12
    StockCountRequest:
      required:
        - packageNumbers
      type: object
      properties:
        packageNumbers:
          type: array
          description: List of package numbers
          items:
            type: integer
            description: List of package numbers
            format: int32
    StockCountResponse:
      required:
        - stockCounts
      type: object
      properties:
        stockCounts:
          type: array
          items:
            $ref: '#/components/schemas/StockCount'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic